config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get "pages/scan_info", to: "pages#scan_info", as: :scan_info
  resources :user_documents, only: %i[index create show edit destroy] do
    member do
      patch 'pay'
      patch 'unpaid'
    end
  end
  resources :user_documents, only: %i[update]
  # patch "user_documents/:id", to: "user_documents#update", as: :user_document_update
  resources :documents, only: %i[index show create]
  # GET   /profile => profiles#show
  resource :profile, only: [ :show ]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show]
  skip_after_action :verify_authorized

  def show
    # authorize @user
    skip_authorization
    @user_documents = UserDocument.where(user_id: current_user.id)
    @user_document = UserDocument.new

    @documents = Document.all

    @general_stats = UserDocument.general_bills(current_user)
    @gas_stats = UserDocument.search_stats("Tokyo Gas", current_user)
    @electricity_stats = UserDocument.search_stats("Tokyo Electricity", current_user)
    @water_stats = UserDocument.search_stats("Tokyo Water", current_user)
    @insurance_stats = UserDocument.search_stats("National Health Insurance", current_user)
    @tax_stats = UserDocument.search_stats("National Health Insurance", current_user)

    @sort_by = ["Date Added", "Due Date", "Cost: High to Low", "Cost: Low to High"]
    @categories = ["all"]
    @collection_type = params[:sort_by]

    unless params[:category]
      params[:category] = "all"
    end

    if @user_documents.exists?
      @user_documents.each do |doc|
        @categories << doc.document.company_name unless doc.document.nil?
      end

      @categories.uniq!
      @collection_type = params[:sort_by]

      unless params[:category] == "all"
        @user_documents = @user_documents.reject { |doc| doc.document.company_name != params[:category] }
      end

     @user_documents = if params[:category] == "all"
        if params[:sort_by] == "Date Added"
          @user_documents.sort_by { |doc| doc.due_date }
        elsif params[:sort_by] == "Due Date"
          @user_documents.sort_by { |doc| doc.due_date }
        elsif params[:sort_by] == "Cost: High to Low"
          @user_documents.sort_by { |doc| -doc.current_due_amount }
        elsif params[:sort_by] == "Cost: Low to High"
          @user_documents.sort_by { |doc| doc.current_due_amount }
        else
          @user_documents
        end
      else
        @user_documents
      end
    end
  end

  def update
    authorize @user
    @user.update(user_params)
  end

  def update
    authorize @user
    @user.update(user_params)

    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end

  def set_user
    @user = current_user
  end
end

app/views/profiles/_bill-list.html.erb
<div class="bills-list__item">
  <%= link_to "", user_document_path(user_document), class: "bills-list__link",
  method: :get %>
  <div class="bills-list__company">
    <% if user_document.document.company_name %>
       <%= user_document.document.company_name %> 
    <% else %>
        "Unrecognizable Bill, Sorry"
    <% end %>
  </div>
  <div class="bills-list__due-date">
    <%= user_document.due_date.strftime("%b %d, %Y") %>
  </div>
  <div class="bills-list__due">
    ¥<%= number_with_delimiter user_document.current_due_amount %>
  </div>
  <div class="bills-list__paid">
    <% if user_document.state %>
    <p class="bills-list__status">Paid</p>
    <% end %>
  </div>
</div>

app/views/profiles/_due-bills.html.erb
<% unless user_document.state %>
<div class="upcoming-card__data">
  <div class="upcoming-card__title">
      <% unless user_document.document.nil? %>
        <%= link_to user_document.document.company_name,
        user_document_path(user_document), class: "upcoming-card__link", method:
        :get %>
      <% end %>
  </div>
  <div class="upcoming-card__content">
    <div class="upcoming-card__label">
      Due on
    </div>
    <div class="upcoming-card__info">
      <%= user_document.due_date.strftime("%b %d %Y") unless user_document.due_date.nil? %>
    </div>
  </div>
  <div class="upcoming-card__content">
    <div class="upcoming-card__label">
      Amount due
    </div>
    <div class="upcoming-card__info">
      ¥<%= number_with_delimiter(user_document.current_due_amount) %>
    </div>
  </div>
  <%= button_to "Mark As Paid", pay_user_document_path(user_document), method:
  :patch, class: "button is-small z-index", remote: true, id:
  "#{user_document.id}-paid-document" %>
</div>
<% end %>

app/views/profiles/_due-card.html.erb
<div class="col-xs-12 col-md-4">
  <div class="due-card">
    <% unless @user_document.state %>
    <div class="due-card__type">
      <div class="due-card__subtitle">
       <% if user_document.document.company_name %>
          <%= user_document.document.company_name %>
       <% else %>
           "Unrecognizable Bill, Sorry"
       <% end %>
      </div>
    </div>
    <div class="due-card__price">
      <%= @user_document.current_due_amount %> Yen
    </div>
    <div class="due-card__date">
      <div class="due-card__title">
        Due:<strong>
          <%= @user_document.due_date.strftime("%b %d %Y") %></strong
        >
      </div>
    </div>
    <div class="due-card__remaining-days">
      <div class="due-card__title">
        Days Remaining: <%= (@user_document.due_date - Date.today).positive? ?
        (@user_document.due_date - Date.today).to_i : "Overdue" %>
      </div>
      <div class="due-card__image">
        <%= cl_image_tag @user_document.photo.url, :width => 600, :crop =>
        "fill" %>
      </div>
    </div>

    <%= link_to "paid", pay_user_document_path(@user_document), method: :patch,
    remote: true, id: "#{@user_document.id}-paid-document" %> <% end %>
  </div>
</div>

app/views/profiles/_due-cards.html.erb
<div class="col-xs-12 col-md-4">
  <div class="due-card">
    <% unless user_document.state %>
    <div class="due-card__type">
      <div class="due-card__subtitle">
       <% if user_document.document.company_name %>
          <%= user_document.document.company_name %>
       <% else %>
           "Unrecognizable Bill, Sorry"
       <% end %>
      </div>
    </div>
    <div class="due-card__price">
      <%= user_document.current_due_amount %> Yen
    </div>
    <div class="due-card__date">
      <div class="due-card__title">
        Due:<strong> <%= user_document.due_date.strftime("%b %d %Y") %></strong>
      </div>
    </div>
    <div class="due-card__remaining-days">
      <div class="due-card__title">
        Days Remaining: <%= (user_document.due_date - Date.today).positive? ?
        (user_document.due_date - Date.today).to_i : "Overdue" %>
      </div>
    </div>

    <%= link_to "paid", pay_user_document_path(user_document), method: :patch,
    remote: true, id: "#{user_document.id}-paid-document" %> <% end %>
  </div>
</div>

app/views/profiles/_paid.html.erb
<% if user_document.state %>
  <p class="tag">Paid</p>
  <%= link_to "Wait, I haven't paid this...", unpaid_user_document_path(user_document), method: :patch, remote: true, id: "#{user_document.id}-unpaid-document"  %>
<% else %>
  <p class="tag">Not Paid</p>
  <%= link_to "Mark as Paid", pay_user_document_path(user_document), method: :patch, remote: true, id: "#{user_document.id}-paid-document"  %>
<% end %>

app/views/profiles/_stats.html.erb
<div class="profile-stats__heading">
  <h5><%= title %> Bills</h5>
  <i class="profile-stats__display fas fa-chevron-circle-down"></i>
</div>
<div class="profile-stats__data">
  <div class="profile-stats__highest">
    <h5>Highest</h5>
    <p>¥<%= number_with_delimiter(stats[:max]) %></p>
  </div>
  <div class="profile-stats__lowest">
    <h5>Lowest</h5>
    <p>¥<%= number_with_delimiter(stats[:min]) %></p>
  </div>
  <div class="profile-stats__average">
    <h5>Average</h5>
    <p>¥<%= number_with_delimiter(stats[:average]) %></p>
  </div>
</div>

app/views/profiles/_total-stats.html.erb
<div class="user-card__data">
  <div class="user-card__title">
    Bills <%= title %>
  </div>
  <div class="user-card__count <%= modifier %>">
    <%= count %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="primary-wrapper is-paddingless has-color">
    <div class="profile">

      <div class="sticky-top profile__left">

        <div class="user-card">
          <div class="user-card__header">
            <% unless current_user.photo.url.nil? %>
            <%= cl_image_tag current_user.photo, class: "avatar" %>
            <% else %>
            <%= image_tag 'avatar.png', class: "avatar" %>
            <% end %>
          </div>
          <div class="user-card__body center-content">
            <%= link_to 'Edit profile',
            edit_user_registration_path(current_user), class: "user-card__edit
            tag" %>
            <div class="user-card__heading">
              <%= current_user.first_name %> <%= current_user.last_name %>
            </div>
            <div class="user-card__info">

              <%= render "total-stats", title: "Uploaded", count: current_user.user_documents.count, modifier: "" %>

              <%= render "total-stats", title: "Paid", count: current_user.user_documents.select { |doc| doc.state == true }.count, modifier: "" %>

              <%= render "total-stats", title: "Unpaid", count: current_user.user_documents.select { |doc| doc.state == false }.count, modifier: "" %>
              
              <%= render "total-stats", title: "Overdue", count: current_user.user_documents.select { |doc| doc.document.nil? ? "Unrecognized" : (doc.due_date - Date.today).positive? && doc.state == false }.count, modifier: "user-card__count--red" %>

            </div>
          </div>
          <%= simple_form_for(@user_document) do |f| %>
            <%= f.input :photo, required: true, label: 'Bill upload/snap', required: false, input_html: { class: "upload-document hidden", onchange: "loader()" }, label_html: { class: 'upload-photo' }, label: '📷 Upload a Bill' %>
            <%= f.input :photo_cache, as: :hidden %>
          <% end %>

          <div class="profile-stats">
            <h2>Financial Data for <%= Time.current.year %> </h2>
            <%= render "stats", title: "All", stats: @general_stats  %>
            <%= render "stats", title: "Gas", stats: @gas_stats  %>
            <%= render "stats", title: "Water", stats: @water_stats  %>
            <%= render "stats", title: "Electricity", stats: @electricity_stats  %>
            <%= render "stats", title: "Tax", stats: @tax_stats  %>
            <%= render "stats", title: "Insurance", stats: @insurance_stats  %>
          </div>
        </div>
      </div>

      <div class="has-background-primary profile__right">

        <div class="upcoming-card">
          <div class="upcoming-card__heading">
            <h2> Your upcoming bills</h2>
          </div>
          <div class="upcoming-card__body">
              <% sorted = current_user.user_documents.where(state: false).order('due_date ASC').first(3) %>
              <% p sorted %>
              <% sorted.each do |user_document| %>
                <% if user_document.created_at.year == Date.today.year %>
                <%= render "due-bills", user_document: user_document %>
                <% end %>
              <% end %>

          </div>
        </div>

        <div class="has-background-primary profile__bills">
            <div class="filter">
              <%= form_tag profile_path, method: :get, class: "filter__form" do |f| %>
                <%= select_tag "sort_by", options_for_select(@sort_by, params[:sort_by]), id: "sort-by-select" %>
                <%= select_tag "category", options_for_select(@categories, params[:category]), id: "category-select" %>
              <% end %>

              <div class="bills-list">
                <div class="bills-list__header">
                 <div class="bills-list__company">
                    Bill Type
                  </div>
                  <div class="bills-list__due-date">
                    Due date
                  </div>
                  <div class="bills-list__due">
                    Amount Due
                  </div>
                  <div class="bills-list__paid">
                    State
                  </div>
                </div>

                <% @user_documents.select do |user_document| %>
                  <% if user_document.state == true %>
                    <% if @collection_type == 'due date' %>
                      <%= render "bill-list", user_document: user_document %>
                    <% elsif @collection_type == 'most expensive' %>
                      <%= render "bill-list", user_document: user_document %>
                    <% elsif @collection_type == 'least expensive' %>
                      <%= render "bill-list", user_document: user_document %>
                    <% else %>
                      <%= render "bill-list", user_document: user_document %>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>
        </div>
      </div>

    </div>
  </div>
</div>

<script>
  $( "#sort-by-select" ).select2({
    theme: "bootstrap",
  });
  $( "#sort-by-select").on('select2:select', (e) => {
    document.querySelector(".filter__form").submit();
  });
  $( "#category-select").select2({
    theme: "bootstrap"
  });
  $( "#category-select").on('select2:select', (e) => {
    document.querySelector(".filter__form").submit();
  });
</script>

app/views/profiles/update.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>

const paid = document.querySelector("#checkbox_user_document_15");

paid.addEventListener("click", e => {
  console.log("hello");
})