config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get "pages/scan_info", to: "pages#scan_info", as: :scan_info
  resources :user_documents, only: %i[index create show edit destroy] do
    member do
      patch 'pay'
      patch 'unpaid'
    end
  end
  resources :user_documents, only: %i[update]
  # patch "user_documents/:id", to: "user_documents#update", as: :user_document_update
  resources :documents, only: %i[index show create]
  # GET   /profile => profiles#show
  resource :profile, only: [ :show ]
end

app/views/pages/home.html.erb
<% content_for :meta_title, "siji bills - No language barrier" %>
<% content_for :meta_description, "Take the guesswork out of Japanese bills." %>
<% content_for :meta_image, "meta_image_shrine.jpg" %>

<% content_for(:navbar_class, "navbar-home")%>
<div class="banner">
  <div class="banner__header">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6 is-paddingless">
          <h1 class="banner__heading" style="margin-top: -20px;" >
           siji
          </h1>
          <div class="card">
            <div class="result">
              <ul style="list-style: none;">
                <li><p class="card__title"><strong>Water bill</strong></p></li>
                <li>
                  <p><strong>¥ 16,026 </strong></p>
                </li>
                <li>
                  <p>Due: <strong>May 18</strong></p>
                </li>
              </ul>
            </div>
            <div class="result-photo">
              <%= image_tag 'pic_water.png' %>
            </div>
          </div>
        </div>

        <div class="col-xs-12 col-md-6 banner__text">
          <p class="banner__description">
            Take the guesswork out of Japanese bills
          </p>
        </div>
        <div>
          <%= link_to 'Try now', scan_info_path, class: 'try-now' %>
          </div>
          <div class="down-arrow">
            <i class="material-icons">
              keyboard_arrow_down
            </i>
          </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row padding-top-bottom">
    <div class="col-xs-12 center-content">
      <h1>
        What we offer...
      </h1>
    </div>
    <div class="col-xs-12 col-md-4">
      <h2 class="center-content">Recognition</h2>
      <div class="card">
        <%= link_to scan_info_path do %>
        <div class="card-body scan">
          <div class="card-icon">
            <i class="material-icons">
              linked_camera
            </i>
          </div>
        </div>
        <% end %>
        <div class="card-footer">
          <p>
            Simply take a photo, or upload one of your Japanese
            bill and we'll get the most relevant information for you.
          </p>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <h2 class="center-content">Records</h2>
      <div class="card">
        <%= link_to profile_path(current_user) do %>
        <div class="card-body record">
          <div class="card-icon">
          <i class="material-icons">
            insert_chart
          </i>
        </div>
        </div>
        <% end %>
        <div class="card-footer">
          <p>
            Have statistics on your past payments readily available at the click of a button. Know how much you spend each month.
          </p>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
      <h2 class="center-content">Reminders</h2>
      <div class="card">
        <%= link_to user_documents_path(current_user) do %>
        <div class="card-body track">
          <div class="card-icon">
          <i class="material-icons">
            email
          </i>
          </div>
        </div>
        <% end %>
        <div class="card-footer">
          <p>
            Keep up to date with when your next bill is due with our tracking
            and notification system.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/scan_info.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">

      <h2 class="center-content">Take a photo or upload one</h2>
       <%= simple_form_for(@user_document) do |f| %>
        <%= f.input :photo, required: true, label: 'Bill upload/snap', required: false, input_html: { class: "upload-document hidden", onchange: "loader()" }, label_html: { class: 'upload-photo' }, label: '📷 Upload a Bill' %>
        <%= f.input :photo_cache, as: :hidden %>
      <% end %>
    </div>
  </div>
</div>

<!--   <div class="col-sm-6 col-sm-offset-3" >
    <video id = "video" ></video>
    <a href="#" id="capture" class= "button is-big" >Take Photo</a>
    <a href="#" id="submitOwn" class= "button is-big" >Photo is OK</a>
    <canvas id = "canvas" ></canvas>
    <img id = "photo" src="" alt=""> -->
      <!-- <script>

      const constraints = { audio: false, video: true };
      const canvas = document.getElementById('canvas'),
            context = canvas.getContext('2d'),
            photo = document.getElementById('photo'),
            photoForm = document.getElementById('new_user_document'),
            photoInput = document.getElementById('user_document_photo');

      navigator.mediaDevices.getUserMedia(constraints)
      .then(function(mediaStream) {
        var video = document.querySelector('video');
            video.srcObject = mediaStream;
        video.onloadedmetadata = function(e) {
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          video.play();
        };
      })
      .catch(function(err) { console.log(err.name + ": " + err.message);
      });

      function takePhoto(){
        context.drawImage(video, 0, 0);
        photo.setAttribute('src', canvas.toDataURL('image/png'));
      }

      document.getElementById('capture').addEventListener('click', takePhoto);
      document.getElementById('video').addEventListener('click', takePhoto);

      document.getElementById('submitOwn').addEventListener('click', function(e){

        const formData = new FormData(photoForm);
        canvas.toBlob((blob) => {
          formData.set("user_document[photo]", blob, 'image.png');
          const request = new XMLHttpRequest();
          request.open("POST", photoForm.action);
          request.send(formData);
          request.onload = (event) => {
            console.log(event);
            window.location = event.currentTarget.responseURL;
          };
        });
      });

      </script> -->
  </div>
</div>