config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  get "pages/scan_info", to: "pages#scan_info", as: :scan_info
  resources :user_documents, only: %i[index create show edit destroy] do
    member do
      patch 'pay'
      patch 'unpaid'
    end
  end
  resources :user_documents, only: %i[update]
  # patch "user_documents/:id", to: "user_documents#update", as: :user_document_update
  resources :documents, only: %i[index show create]
  # GET   /profile => profiles#show
  resource :profile, only: [ :show ]
end

app/models/document.rb
class Document < ApplicationRecord
  has_many :user_documents
  validates :jp_name, uniqueness: true, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: [:index, :show]

  def index
    @documents = policy_scope(Document).order(created_at: :desc)
  end

  def show
    @document = Document.find(params[:id])
  end

  # def new
  #   @document = Document.new
  #   authorize @document
  # end

  def create
    @document = Document.new(document_params)
    authorize @document

    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render :new
    end
  end

  def document_params
    params.require(:document).permit(:jp_name, :company_name, :payment_type, :description)
  end
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/index.html.erb
<div class="container">
    <h1>Documents#index</h1>
    <p>Find me in app/views/documents/index.html.erb</p>
    <% @documents.each do |document|%>
      <h3><%= link_to document.jp_name, document_path(document), method: "get"%></h3>
      <p><strong>Company name: </strong><%= document.company_name %></p>
      <p><strong>Payment type: </strong><%= document.payment_type %></p>
      <p><strong>Document description: </strong></p>
      <p><%= document.description %></p>
    <br>
    <% end %>
</div>

app/views/documents/show.html.erb
<div class="container">
    <h1>Documents#show</h1>
      <h2><%= @document.jp_name%></h2>
      <p><strong>Payment type: </strong><%= @document.payment_type %></p>

      <p><strong>Company name: </strong><%= @document.company_name %></p>

      <p><strong>Document description: </strong></p>
      <p><%= @document.description %></p>
    <br>
    <%= button_to "Back to All documents", documents_path , method: "get"%>
</div>